export const platformNames = {
  '36kr': '36氪',
  '51cto': '51CTO',
  '52pojie': '吾爱破解',
  'acfun': 'AcFun',
  'baidu': '百度',
  'bilibili': '哔哩哔哩',
  'coolapk': '酷安',
  'csdn': 'CSDN',
  'dgtle': '数字尾巴',
  'douban-group': '豆瓣小组',
  'douban-movie': '豆瓣电影',
  'douyin': '抖音',
  'earthquake': '地震速报',
  'gameres': '游资网',
  'geekpark': '极客公园',
  'genshin': '原神',
  'github': 'GitHub',
  'guokr': '果壳',
  'hackernews': 'Hacker News',
  'hellogithub': 'HelloGitHub',
  'history': '历史上的今天',
  'honkai': '崩坏3',
  'hostloc': 'HostLoc',
  'hupu': '虎扑',
  'huxiu': '虎嗅',
  'ifanr': '爱范儿',
  'ithome-xijiayi': 'IT之家(喜加一)',
  'ithome': 'IT之家',
  'jianshu': '简书',
  'juejin': '稀土掘金',
  'kuaishou': '快手',
  'linuxdo': 'LinuxDo',
  'lol': '英雄联盟',
  'miyoushe': '米游社',
  'netease-news': '网易新闻',
  'newsmth': '水木社区',
  'ngabbs': 'NGA',
  'nodeseek': 'NodeSeek',
  'nytimes': '纽约时报',
  'producthunt': 'Product Hunt',
  'qq-news': '腾讯新闻',
  'sina-news': '新浪新闻',
  'sina': '新浪',
  'smzdm': '什么值得买',
  'sspai': '少数派',
  'starrail': '崩坏：星穹铁道',
  'thepaper': '澎湃新闻',
  'tieba': '百度贴吧',
  'toutiao': '今日头条',
  'v2ex': 'V2EX',
  'weatheralarm': '天气预警',
  'weibo': '微博',
  'weread': '微信读书',
  'yystv': '游研社',
  'zhihu-daily': '知乎日报',
  'zhihu': '知乎'
}

// 获取平台中文名，如果没有映射则返回原名
export function getPlatformName(platformKey) {
  return platformNames[platformKey] || platformKey
}